apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-md-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: dineshkumar27/webapp21:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-svc
spec:
  selector:
    app: mywebapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
