apiVersion: v1
kind: Pod
metadata:
  name: mywebapp
  labels:
    app: mywebapp
spec:
  containers:
    - name: mywebapp
      image: dineshkumar27/webapp21:2.0
      ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: mywebapp
spec:
  selector:
    app: mywebapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer   
